### ISSUE TITLE
Crash on macOS 11.3

### ISSUE THREAD

**Issue by gotzlotz** [nahiyan/torrenter#1]
Crash on startup. can send problem report in needed.

**Comment by gotzlotz** [comment]
same on 11.4

**Comment by nahiyan** [comment]
Thank you for letting me know about this. I'll work on it when I'll get some time off. Busy maintaining my other projects along with active development. If you can please provide more details, it'd be great.

**Comment by gotzlotz** [comment]
Will send the error message and log in a few.

**Comment by gotzlotz** [comment]
Process:               Torrenter [16537]
Path:                  /Applications/Torrenter.app/Contents/MacOS/Torrenter
Identifier:            io.github.hedronium.Torrenter
Version:               0.1.0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Torrenter [16537]
User ID:               501

Date/Time:             2021-06-06 03:35:04.013 -0700
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Bridge OS Version:     5.4 (18P4663)
Anonymous UUID:        34DD60DB-60C0-2E92-190E-B5797B23591E

Sleep/Wake UUID:       35A931CD-69B5-46DF-A1D1-DD826AEFACE8

Time Awake Since Boot: 16000 seconds
Time Since Wake:       280 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 4A889CE9-8D7E-304E-A5F7-84D819B0BF9C
Library not loaded: /usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib
  Referenced from: /Applications/Torrenter.app/Contents/Frameworks/libtorrent-rasterbar.1.2.4.dylib
  Reason: image not found

Binary Images:
       0x10e29a000 -        0x10e2d1fff +io.github.hedronium.Torrenter (0.1.0) <E24CF1F5-E765-3E2A-9C93-D5008A6B9F99> /Applications/Torrenter.app/Contents/MacOS/Torrenter
       0x10e2f8000 -        0x10e2fbfff +libmaxminddb.0.dylib (0) <882C8B72-BE2B-317E-9E42-C22E02F95D36> /Applications/Torrenter.app/Contents/Frameworks/libmaxminddb.0.dylib
       0x10e30b000 -        0x10e61cfff +libtorrent-rasterbar.1.2.4.dylib (0) <DDCE9237-FDF8-3BF5-85ED-A678CA92D421> /Applications/Torrenter.app/Contents/Frameworks/libtorrent-rasterbar.1.2.4.dylib
       0x116a8c000 -        0x116b27fff  dyld (852) <1AC76561-4F9A-34B1-BA7C-4516CACEAED7> /usr/lib/dyld
    0x7fff200f9000 -     0x7fff200fafff  libsystem_blocks.dylib (79) <48AF56A9-6E42-3A5E-A213-E6AFD8F81044> /usr/lib/system/libsystem_blocks.dylib
    0x7fff200fb000 -     0x7fff20130fff  libxpc.dylib (2038.120.1) <5751A7F5-6DC5-3090-B7F1-D90ED71BEF1F> /usr/lib/system/libxpc.dylib
    0x7fff20131000 -     0x7fff20148fff  libsystem_trace.dylib (1277.120.1) <8E243C00-BFC2-3FAA-989C-0D72314DB04D> /usr/lib/system/libsystem_trace.dylib
    0x7fff20149000 -     0x7fff201e6fff  libcorecrypto.dylib (1000.120.2) <FADB19A0-1BF3-3F47-B729-87B4FA8CA677> /usr/lib/system/libcorecrypto.dylib
    0x7fff201e7000 -     0x7fff20213fff  libsystem_malloc.dylib (317.121.1) <CAD162A5-7367-3A30-9C15-5D036411AEDE> /usr/lib/system/libsystem_malloc.dylib
    0x7fff20214000 -     0x7fff20258fff  libdispatch.dylib (1271.120.2) <7B229797-1F2E-3409-9D0C-060C7EEF2E12> /usr/lib/system/libdispatch.dylib
    0x7fff20259000 -     0x7fff20292fff  libobjc.A.dylib (824) <FE5AF22E-80A1-34BB-98D6-610879988BAA> /usr/lib/libobjc.A.dylib
    0x7fff20293000 -     0x7fff20295fff  libsystem_featureflags.dylib (28.60.1) <77F7F479-39BD-3111-BE3C-C74567FD120C> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff20296000 -     0x7fff2031efff  libsystem_c.dylib (1439.100.3) <38F8A126-C995-349A-B909-FF831914ED2E> /usr/lib/system/libsystem_c.dylib
    0x7fff2031f000 -     0x7fff20374fff  libc++.1.dylib (905.6) <B3812B86-4FCF-3A10-8866-DF67940A974C> /usr/lib/libc++.1.dylib
    0x7fff20375000 -     0x7fff2038afff  libc++abi.dylib (905.6) <A0FE88B7-E157-3C9C-A29A-11D3BE3436B3> /usr/lib/libc++abi.dylib
    0x7fff2038b000 -     0x7fff203bafff  libsystem_kernel.dylib (7195.121.3) <A4938CF5-ABC0-397B-8A6E-B7BEEFA24D0A> /usr/lib/system/libsystem_kernel.dylib
    0x7fff203bb000 -     0x7fff203c6fff  libsystem_pthread.dylib (454.120.2) <17482C9D-061E-3769-AC9E-BE1239D33098> /usr/lib/system/libsystem_pthread.dylib
    0x7fff203c7000 -     0x7fff20402fff  libdyld.dylib (852) <C10CEA28-D5A0-324F-8F07-8C7CE4805412> /usr/lib/system/libdyld.dylib
    0x7fff20403000 -     0x7fff2040cfff  libsystem_platform.dylib (254.80.2) <8664A4CD-EE27-3C71-B5CC-06E2B1B4F394> /usr/lib/system/libsystem_platform.dylib
    0x7fff2040d000 -     0x7fff20438fff  libsystem_info.dylib (542.40.3) <EA3F9C9C-3116-3DB4-A3F1-5B03172C1E72> /usr/lib/system/libsystem_info.dylib
    0x7fff20439000 -     0x7fff208d6fff  com.apple.CoreFoundation (6.9 - 1776.103) <01EFB7F8-BCE6-32DF-A0B8-02F9027F882C> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff20efa000 -     0x7fff20f77fff  com.apple.SystemConfiguration (1.20 - 1.20) <81EDA68C-051A-3F4C-B79E-B53B365B67B1> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff211e6000 -     0x7fff21544fff  com.apple.Foundation (6.9 - 1776.103) <3C3B967D-778D-30BF-A3F8-E734FAFD76F2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff22802000 -     0x7fff2280bfff  libsystem_darwin.dylib (1439.100.3) <BF5B5FD8-B5A3-3035-8641-466E625A6CE8> /usr/lib/system/libsystem_darwin.dylib
    0x7fff22c21000 -     0x7fff22c2cfff  libsystem_notify.dylib (279.40.4) <7FFECC25-FA84-3B59-9CC8-4D9DC84E6EC1> /usr/lib/system/libsystem_notify.dylib
    0x7fff22c7b000 -     0x7fff239c3fff  com.apple.AppKit (6.9 - 2022.50.114) <02279013-2888-3A1D-8F28-0C39A64EF5FA> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff24bb6000 -     0x7fff24bc4fff  libsystem_networkextension.dylib (1295.120.5) <02486B74-EAAD-3055-AE20-F12E79B39297> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff24c23000 -     0x7fff24c39fff  libsystem_asl.dylib (385) <B3E89650-A7FE-3E93-8A1B-D88145FDD45C> /usr/lib/system/libsystem_asl.dylib
    0x7fff24fb7000 -     0x7fff25640fff  com.apple.CoreGraphics (2.0 - 1463.14.2) <8E1776B9-0046-3FCF-BF54-F76490EA4A27> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff25b3a000 -     0x7fff25f59fff  com.apple.CoreData (120 - 1048) <D3DAFFD5-CC38-3A82-B138-015DBFD551D9> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff262fe000 -     0x7fff26305fff  libsystem_symptoms.dylib (1431.120.1) <3BEA5355-D267-39D4-8BC6-A1703845BD3F> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff2830c000 -     0x7fff2831cfff  libsystem_containermanager.dylib (318.100.4) <2BBFF58C-D27E-3371-968D-7DE1E53749F6> /usr/lib/system/libsystem_containermanager.dylib
    0x7fff29024000 -     0x7fff29027fff  libsystem_configuration.dylib (1109.120.1) <C7A9BD10-192B-31D3-92ED-2581A61A99F6> /usr/lib/system/libsystem_configuration.dylib
    0x7fff29028000 -     0x7fff2902cfff  libsystem_sandbox.dylib (1441.120.5) <DC075A7C-9D4A-32D3-9022-CD47764AFDAD> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff29d1e000 -     0x7fff29d20fff  libquarantine.dylib (119.40.2) <4611645F-5817-3A80-8382-2DB03A8C0141> /usr/lib/system/libquarantine.dylib
    0x7fff2a2c9000 -     0x7fff2a2cdfff  libsystem_coreservices.dylib (127.1) <1E2DA16B-D528-3D43-86C2-2BB9127954A0> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff2a4dd000 -     0x7fff2a524fff  libsystem_m.dylib (3186.100.3) <21949128-D4E6-3179-B248-41B05C1CE102> /usr/lib/system/libsystem_m.dylib
    0x7fff2a526000 -     0x7fff2a52bfff  libmacho.dylib (980) <3677B3B7-03E8-3804-B2FE-5640B18FE40E> /usr/lib/system/libmacho.dylib
    0x7fff2a548000 -     0x7fff2a553fff  libcommonCrypto.dylib (60178.120.3) <BBA72D86-B9C1-3123-AE59-D629DE278695> /usr/lib/system/libcommonCrypto.dylib
    0x7fff2a554000 -     0x7fff2a55efff  libunwind.dylib (201) <3149D79A-911B-39ED-9C93-6C7E6B0860C7> /usr/lib/system/libunwind.dylib
    0x7fff2a55f000 -     0x7fff2a566fff  liboah.dylib (203.46) <0A17EAFC-15E9-37FE-8EE2-DE0F7F220AD8> /usr/lib/liboah.dylib
    0x7fff2a567000 -     0x7fff2a571fff  libcopyfile.dylib (173.40.2) <7304CA0D-E93C-367F-9BEE-AC56B873F06C> /usr/lib/system/libcopyfile.dylib
    0x7fff2a572000 -     0x7fff2a579fff  libcompiler_rt.dylib (102.2) <0DB1902E-C79C-3E26-BE51-F70960ECF0B9> /usr/lib/system/libcompiler_rt.dylib
    0x7fff2a57a000 -     0x7fff2a57cfff  libsystem_collections.dylib (1439.100.3) <E180C04A-9CFB-3C8E-9C2B-978D23A99F2A> /usr/lib/system/libsystem_collections.dylib
    0x7fff2a57d000 -     0x7fff2a57ffff  libsystem_secinit.dylib (87.60.1) <8C33D323-C11C-34CB-9295-4D7C98B8AFD6> /usr/lib/system/libsystem_secinit.dylib
    0x7fff2a580000 -     0x7fff2a582fff  libremovefile.dylib (49.120.1) <6DEAEEC9-2A65-3C7B-A9CE-23245772FD07> /usr/lib/system/libremovefile.dylib
    0x7fff2a583000 -     0x7fff2a583fff  libkeymgr.dylib (31) <FD167835-3829-3FFD-B13E-D18113E271AB> /usr/lib/system/libkeymgr.dylib
    0x7fff2a584000 -     0x7fff2a58bfff  libsystem_dnssd.dylib (1310.120.71) <7BB607FE-EF79-3144-8BD0-A66792FF1443> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff2a58c000 -     0x7fff2a591fff  libcache.dylib (83) <8B201058-2C34-3C12-9A7A-898CB0AAD150> /usr/lib/system/libcache.dylib
    0x7fff2a592000 -     0x7fff2a593fff  libSystem.B.dylib (1292.120.1) <A8309074-31CC-31F0-A143-81DF019F7A86> /usr/lib/libSystem.B.dylib
    0x7fff2c769000 -     0x7fff2cb3ffff  libswiftCore.dylib (5.4 - 1205.0.24.15) <9A598760-3D5C-3CE9-A3BF-E5009845A6CD> /usr/lib/swift/libswiftCore.dylib
    0x7fff2d999000 -     0x7fff2d999fff  liblaunch.dylib (2038.120.1) <FB6430FC-AACB-3AFF-8763-4C5AFABEF40E> /usr/lib/system/liblaunch.dylib
    0x7fff2fe28000 -     0x7fff2fe28fff  libsystem_product_info_filter.dylib (8.40.1) <D5194AB1-61C4-3C8D-9E3C-C65702BAB859> /usr/lib/system/libsystem_product_info_filter.dylib
    0x7fff30471000 -     0x7fff305c9fff  libswiftFoundation.dylib (25.103) <AD60EE7C-4F8F-39C2-B5C7-B9C34CED347D> /usr/lib/swift/libswiftFoundation.dylib
    0x7fff33534000 -     0x7fff33535fff  libswiftObjectiveC.dylib (3) <616E3D5A-1711-3A27-B3D6-149A35526CB5> /usr/lib/swift/libswiftObjectiveC.dylib
    0x7fff3be7c000 -     0x7fff3be86fff  libswiftCoreGraphics.dylib (2) <B4CFA518-EB59-3BAC-B97E-27CCB0B7A498> /usr/lib/swift/libswiftCoreGraphics.dylib

Model: MacBookPro15,1, BootROM 1554.120.19.0.0 (iBridge: 18.16.14663.0.0,0), 6 processors, 6-Core Intel Core i7, 2.2 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro555XItem, Radeon Pro 555X, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, Micron, 8ATF1G64HZ-2G6E1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 16 2021 02:10:42 version 9.30.444.10.32.5.67 FWID 01-a00c1314
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5

**Comment by nahiyan** [comment]
Thank you so much for being so cooperative. This issue has been clearly caused due to the cryptographic library's binary, `/usr/local/opt/libgcrypt/lib/libgcrypt.20.dylib`, one of libtorrent's dependencies, not existing in your system, which shouldn't be assumed to exist with the exact filename in the first place. I'll first upgrade to macOS 11.4 and work on fixing the link to the library very soon. Sorry for taking so long to respond to you.

**Comment by gotzlotz** [comment]
No problem and thanks for taking a look.

**Comment by nahiyan** [comment]
Hello! I posted a [new release](https://github.com/nahiyan/torrenter/releases/tag/v0.2.0) that should fix the issues that you mentioned. I'd really appreciate it if you could try it out and let me know. Thanks!

**Comment by gotzlotz** [comment]
Ok, will try in a hour or so. Will keep you updated.

Update 
It works!!!! one thing, is there setting?

**Comment by nahiyan** [comment]
Awesome! As for settings: unfortunately, no. This is still a pre-release and I work alone on this project. However, if you got any suggestions, let me know. I'll try to bring them out in the next release, very soon. I'll close this issue since it's solved. Please open up a new issue if you want to suggest new features.
